config/routes.rb
DProc::Application.routes.draw do
  
  resources :tasks do
    resources :pages
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :task
  
  validates_attachment_content_type :page_image, :content_type => 'image/jpeg'
  
  has_attached_file :page_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name,        :presence => true,
                          :length => { :minimum => 3}
  validates :description, :presence => true,
                          :length => { :minimum => 5 }
  has_many :pages, :dependent => :destroy        
  
  has_many :tags
 
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }          
                          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  http_basic_authenticate_with :name => "engineer", :password => "engineer", :only => [:destroy]
  
   def create
    @task= Task.find(params[:task_id])
    @page = @task.pages.create(params[:page])
    redirect_to task_path(@task)  
   end
   
   def destroy
    @task= Task.find(params[:task_id])
    @page = @task.pages.find(params[:id])
    @page.destroy
    redirect_to task_path(@task)  
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  http_basic_authenticate_with :name => "engineer", :password => "engineer", :except => [:index, :show]
 
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  
  def join_tags(task)
    task.tags.map { |t| t.name }.join(", ")
  end

end

app/views/home/index.html.erb
<h1>dProc</h1>

<%= link_to "Tasks", tasks_path %>

<h2>rails generate controller home index</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DProc</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for([@task, @task.pages.build ], :html => { :multipart => true }) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>  
  <div class="field">
  	<%= f.file_field :page_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="box">
<table border=0>	
<tr>
	<td>	
		<p>
		   <b>Title:</b> <%= page.title %>
		</p>
	</td>	
	<td rowspan=4>
		<p>
			<%= image_tag page.page_image.url(:thumb) %>
		</p>
	</td>
</tr>
<tr>
	<td>
		<p>   
   			<b>PageID:</b> <%= page.id %>
		</p>
	</td>
	<td></td>
</tr>	

</table>

<p>
  <%= link_to 'Delete Page', [page.task, page],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>
</div>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<% @task.tags.build %>

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => f} %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Reference</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.reference %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>

<h2>Task ID: <%= @task.id %></h2>

</p>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Reference:</b>
  <%= @task.reference %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Tags:</b>
  <%= join_tags(@task) %>
</p>

<h2>Pages</h2>
<%= render @task.pages %>


<h2>Add a page:</h2>
<%= render "pages/form" %>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>